name: Deploy to GitHub Pages

on:
  push:
    branches:
      - 'claude/**'
    paths:
      - 'docs/**'
      - 'chatbot_ui_new_icon-3.html'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync to main branch
        run: |
          git fetch origin main:main || git checkout -b main
          git checkout main
          git checkout ${{ github.ref_name }} -- docs/
          git checkout ${{ github.ref_name }} -- chatbot_ui_new_icon-3.html
          git add docs/ chatbot_ui_new_icon-3.html
          git diff --cached --quiet || git commit -m "Auto-deploy from ${{ github.ref_name }}"
          git push origin main
